{{/*
###############################################################################
# Knative Service
#
# This template creates a Knative Service for serverless deployment.
# Only rendered when knative.enable is true.
# For standard Kubernetes deployments, see deployment.yaml instead.
###############################################################################
*/}}
{{- if .Values.knative.enable }}
kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: {{ include "ibm-connectivity-pack.deploymentName" . }}
  namespace: {{ include "ibm-connectivity-pack.namespace" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    {{- include "ibm-connectivity-pack.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: {{ .Values.knative.minScale | quote }}
        autoscaling.knative.dev/max-scale: {{ .Values.knative.maxScale | quote }}
        autoscaling.knative.dev/scale-down-delay: {{ .Values.knative.scaleDownDelay | quote }}
        autoscaling.knative.dev/metric: {{ .Values.knative.scaleMetric | quote }}
        autoscaling.knative.dev/target: {{ .Values.knative.target | quote }}
        {{- toYaml .Values.annotations | nindent 8 }}
      labels:
        {{- include "ibm-connectivity-pack.labels" . | nindent 8 }}
    spec:
      containerConcurrency: {{ .Values.knative.containerConcurrency }}
      serviceAccountName: {{ include "ibm-connectivity-pack.serviceAccountName" .}}
      imagePullSecrets:
        - name: {{ include "ibm-connectivity-pack.imagePullSecretname" . }}
        - name: ibm-entitlement-key
      containers:
        - {{- include "ibm-connectivity-pack.actionContainer" . | nindent 10 }}
      volumes:
        {{- include "ibm-connectivity-pack.commonVolumes" . | nindent 8 }}
{{- end }}
